# Use an official Node.js runtime as a base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if present) to the working directory
# This allows Docker to cache the npm install step if only source code changes
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application's source code
COPY . .

# Expose the port your application listens on
EXPOSE 5050

# Define the command to run the application when the container starts
CMD ["npm", "start"]
